---
title: "Stress Test"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
---

```{r sssetup, include=FALSE}
library(learnr)
library(data.table)
library(dplyr)
library(pwr)
library(tidyr)
library(stats)
library(ggplot2)
library(tidyverse)
shhh <- suppressPackageStartupMessages
shh <- suppressWarnings
sh <- suppressMessages
knitr::opts_chunk$set(echo = FALSE)
options(digits = 3, scipen = 9999)
tutorial_options(exercise.completion = FALSE,
                 exercise.eval = TRUE,
                 exercise.lines = 8,
                 exercise.diagnostics = TRUE)

Input = ("
Tillamook Newport Petersburg  Magadan Tvarminne
0.0571	0.0873	0.0974	0.1033	0.0703
0.0813	0.0662	0.1352	0.0915	0.1026
0.0831	0.0672	0.0817	0.0781	0.0956
0.0976	0.0819	0.1016	0.0685	0.0973
0.0817	0.0749	0.0968	0.0677	0.1039
0.0859	0.0649	0.1064	0.0697	0.1045
0.0735	0.0835	0.105	  0.0764	NA
0.0659	0.0725	0.0689  NA  NA
0.0923  NA  NA  NA  NA
0.0836  NA  NA  NA  NA
")
mussels <- read.table(textConnection(Input), header = TRUE)
rm(Input)
long_mussels <- pivot_longer(data = mussels,
                             cols = names(mussels),
                             names_to = "location",
                             values_to = "aam")
long_mussels$location <- as.factor(long_mussels$location)
```



```{r ssbb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r ttwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r ttaselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r ttbhow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r ttcpredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r ttdwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r ttewhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r ttftwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r ttgtwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r tthwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r ttitwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r ttjwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```



```{r ttkbb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r uukwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r uulselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r uumhow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r uunpredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r uunwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r uuowhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r uuptwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r uuqtwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r uurwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r uustwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r uutwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```



```{r uuubb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r vvvwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r vvwselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r vvxhow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r vvypredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r vvzwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r vvaawhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r vvaatwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r vvaatwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r vvaawhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r vvaatwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r vvaawhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```



```{r vvaabb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r wwaawhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r wwbbselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r wwbbhow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r wwbbpredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r wwbbwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r wwbbwhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r wwbbtwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r wwbbtwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r wwbbwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r wwbbtwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r wwbbwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```



```{r wwbbbb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r vvbbwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r ccselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r cchow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r ccpredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r ccwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r ccwhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r cctwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r cctwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r ccwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r cctwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r ccwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```



```{r ccbb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r ccwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r ddselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r ddhow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r ddpredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r ddwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r ddwhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r ddtwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r ddtwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r ddwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r ddtwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r ddwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```



```{r ddbb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r ddwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r eeselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r eehow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r eepredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r eewhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r eewhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r eetwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r eetwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r eewhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r eetwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r eewhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```



```{r eebb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r eewhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r ffselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r ffhow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r ffpredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r ffwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r ffwhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r fftwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r fftwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r ffwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r fftwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r ffwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```



```{r ffbb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r ffwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r ggselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r gghow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r ggpredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r ggwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r ggwhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r ggtwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r ggtwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r ggwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r ggtwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r ggwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```


```{r ggbb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r ggwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r hhselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r hhhow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r hhpredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r hhwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r hhwhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r hhtwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r hhtwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r hhwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r hhtwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r hhwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```


```{r hhbb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r hhwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r iiselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r iihow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r iipredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r iiwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r iiwhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r iitwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r iitwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r iiwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r iitwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r iiwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```


```{r iibb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r iiwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r jjselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r jjhow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r jjpredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r jjwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r jjwhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r jjtwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r jjtwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r jjwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r jjtwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r jjwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```


```{r jjbb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r jjwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r kkselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r kkhow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r kkpredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r kkwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r kkwhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r kktwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r kktwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r kkwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r kktwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r kkwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```


```{r kkbb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r kkwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r llselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r llhow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r llpredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r llwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r llwhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r lltwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r lltwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r llwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r lltwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r llwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```


```{r llbb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r llwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r mmselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r mmhow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r mmpredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r mmwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r mmwhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r mmtwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r mmtwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r mmwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r mmtwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r mmwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```


```{r mmbb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r mmwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r nnselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r nnhow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r nnpredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r nnwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r nnwhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r nntwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r nntwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r nnwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r nntwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r nnwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```


```{r nnbb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r nnwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r ooselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r oohow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r oopredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r oowhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r oowhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r ootwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r ootwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r oowhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r ootwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r oowhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```


```{r oobb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r oowhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r ppselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r pphow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r pppredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r ppwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r ppwhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r pptwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r pptwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r ppwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r pptwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r ppwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```


```{r ppbb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r ppwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r qqselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r qqhow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r qqpredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r qqwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r qqwhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r qqtwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r qqtwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r qqwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r qqtwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r qqwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```


```{r qqbb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r qqwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r rrselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r rrhow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r rrpredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r rrwhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r rrwhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r rrtwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r rrtwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r rrwhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r rrtwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r rrwhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```


```{r rrbb, echo=FALSE}
question("Which are examples of a one-way ANOVA null hypotheses?",
         answer("Mean tibia length is the same for each age group of children", correct = TRUE),
         answer("The average monthly electric bill is the same in major cities within the United States", correct = TRUE),
         answer("The average monthly electric bill in Philadelphia, PA is less than what it is in Burlington, VT"),
         answer("The average monthly electric bill in Philadelphia, PA is more than what it is in Burlington, VT"),
         allow_retry = TRUE,
         random_answer_order = TRUE,
         incorrect = "Remember that the one-way ANOVA tests whether the means of the measurement variable are teh same for different groups.",
         correct = "Yes!"
)
```



```{r rrwhentouseANOVA, echo=FALSE}
question("Select the cases where ANOVA is appropriate",
         answer("A professor has three classes and you want to compare the professor's assessment of the three classes in comparison with each other"),
         answer("Three professors have one class each and you want to compare the mean class grades", correct = TRUE),
         answer("You want to compare white blood cell counts as a response to medication for four groups of patients", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "You'll learn about independence between groups later, which matters for an ANOVA, but at this point, using common sense, you might be able to figure out why a design that uses only one professor to fill out assessments comparing three classes might introduce bias. Might comparing the classes against each cause a professor to inflate or deflate ratings to rank the classes rather than objectively assess them? And what about the categorical variable? How many categories does the variable `professor` have? If it has only one, then it is not a variable but a constant. Therefore there are not three groups to compare, but just one: and that just won't work."
)
```


```{r ssselect-variables, echo=FALSE}
question("Which _explicit_ variables do we have in the `mussels` data as it is?",
         answer("Tillamook", correct = TRUE),
         answer("Newport", correct = TRUE),
         answer("Petersburg", correct = TRUE),
         answer("Magadan", correct = TRUE),
         answer("Tvarminne", correct = TRUE),
         answer("aam"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "You found them all!",
         incorrect = "The column names in the dataset `mussels` are the variables."
)
```

```{r sshow-to-modify-data, echo=FALSE}
question("Which variables do we actually want to analyze?",
         answer("location", correct = TRUE),
         answer("aam", correct = TRUE),
         answer("country"),
         answer("city"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "That's right. Just two variables will do the trick.",
         incorrect = "You need only two variables as described in the paragraph above these two questions."
)
```



```{r sspredict-the-finding, echo=FALSE}
question("Looking at the boxplot you just made, what do you think the results of an ANOVA will be?",
         answer("Not all the means are the same among locations.", correct = TRUE),
         answer("All the means are the same among locations.", message = "It's pretty clear from the boxplot that some `location` means are different from at least one other `location` mean."),
         answer("Petersburg and Tvarminne have the same means", message = "Although an ANOVA tells us whether any pairs means differ from each other, it doesn't tell us which pairs. You need a post hoc test to get that additional information."),
         answer("There are two groups of `aam` values", message = "Although you can see clear groups in the boxplot, an ANOVA does not tell you anything about groups. It tells you only that some means differ. You can run a post hoc test to find out more about groupings."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Unfortunately, no.",
         correct = "Yes!"
)
```


```{r sswhat-is-alpha, echo=FALSE}
question("What is `alpha` in the density plot above?",
         answer("A value that tells us what is the cutoff for 'alpha variables'"),
         answer("The family of the colors to use"),
         answer("Color opacity", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Good job!",
         incorrect = "Nope. Try again."
)
```


```{r sswhere-can-we-use-lm, echo=FALSE}
question("Which analyses can you do using the `lm` function?",
         answer("linear regression", correct = TRUE),
         answer("analysis of variance", correct = TRUE),
         answer("analysis of covariance", correct = TRUE),
         answer("Kruskal-Wallis test"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "`lm` is amazing. And so are you!",
         incorrect = "Doing a Kruskal-Wallis test with `lm` would be a bit like vacuuming with a wet mop: It's just not done, for very good reasons."
)
```

```{r sstwo-functions-to-do-anova, echo=FALSE}
question("Which two functions can you use to run an analysis of variance?",
         answer("`stats`", message = "`stats` is a package, not a function."),
         answer("`aov`", correct = TRUE),
         answer("`lm`", correct = TRUE),
         answer("`car`", message = "`car` is a package, not a function."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "You got it!"
)
```
```{r sstwo-packages-to-do-anova, echo=FALSE}
question("Name two packages that can you use to run an analysis of variance (of course there are more---this is R).",
         answer("`stats`", correct = TRUE),
         answer("`anova`", message = "`anova` is a function, not a package."),
         answer("`lm`", message = "`lm` is a function, not a package."),
         answer("`car`", correct = TRUE),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "",
         correct = "All your hard work is paying off!"
)
```


```{r sswhat-to-report, echo=FALSE}
question("Which of these numbers do you include when you report the results of an ANOVA?",
         answer("_p_", correct = TRUE),
         answer("_F_", correct = TRUE),
         answer("df", correct = TRUE),
         answer("the mean squares"),
         random_answer_order = TRUE,
         allow_retry = TRUE
)
```


```{r sstwo-ways-to-summarize-fit, echo=FALSE}
question("Which lines of code result in a summary of the fit for an ANOVA?",
         answer("`summary(aov(aam ~ location, data = long_mussels))`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels); summary(fit)`", correct = TRUE),
         answer("`fit <- aov(aam ~ location, data = long_mussels)`"),
         answer("`aov(aam ~ location, data = long_mussels)`"),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         incorrect = "Here's a hint: In R, you can put multiple commands on the same line using `;` to separate them.",
         correct = "You are amazing!"
)
```


```{r sswhat-does-tukey-kramer-do, echo=FALSE}
question("What does the Tukey-Kramer test tell you?",
         answer("Which pairs of group means are different from each other.", correct = TRUE),
         answer("Whether the critic Tukey liked the movie _Kramer vs. Kramer_."),
         answer("Whether the non-parametric ANOVA is also significant."),
         answer("Whether the ANOVA was significant under the assumptions."),
         random_answer_order = TRUE,
         allow_retry = TRUE,
         correct = "Perfect!",
         incorrect = "Not correct. Read the paragraph just above this question to find the answer."
)
```
